export const providers = [
  {
    provider_id: 'claude',
    provider_name: 'Claude',
    is_enabled: true,
    website_url: 'https://claude.ai/',
    auth_method: ['basic', 'google'],
    connection_type: 'https',
    models: [
      {
        id: 'claude-sonnet-4-5-20250929',
        name: 'Claude Sonnet 4.5',
        is_thinking: false,
        max_context_length: null,
        is_search: false,
        is_image_upload: true,
        is_video_upload: false,
        description:
          "Anthropic's Claude Sonnet 4.5 - Balanced performance for everyday tasks with strong reasoning and image understanding",
      },
      {
        id: 'claude-haiku-4-5-20251001',
        name: 'Claude Haiku 4.5',
        is_thinking: false,
        max_context_length: null,
        is_search: false,
        is_image_upload: true,
        is_video_upload: false,
        description:
          "Anthropic's Claude Haiku 4.5 - Fast, compact model optimized for low-latency responses and efficient processing",
      },
      {
        id: 'claude-sonnet-4-6',
        name: 'Claude Sonnet 4.6',
        is_thinking: false,
        max_context_length: null,
        is_search: false,
        is_image_upload: true,
        is_video_upload: false,
        description:
          "Anthropic's Claude Sonnet 4.6 - Enhanced version with improved accuracy and broader knowledge base",
      },
    ],
    is_pausable: false,
    is_memory: false,
  },
  {
    provider_id: 'deepseek',
    provider_name: 'DeepSeek',
    is_enabled: true,
    website_url: 'https://deepseek.com',
    is_pausable: true,
    auth_method: ['basic', 'google'],
    connection_type: 'https',
    models: [
      {
        id: 'deepseek-instant',
        name: 'DeepSeek Instant',
        is_thinking: true,
        max_context_length: null,
        is_search: true,
        is_image_upload: true,
        is_video_upload: false,
        description:
          'DeepSeek Instant - Fast responses with web search capability and image understanding, supports thinking mode',
      },
      {
        id: 'deepseek-expert',
        name: 'DeepSeek Expert',
        is_thinking: true,
        max_context_length: null,
        is_search: false,
        is_image_upload: false,
        is_video_upload: false,
        description:
          'DeepSeek Expert - Specialized reasoning model with deep analytical capabilities, no search or upload support',
      },
    ],
    is_memory: false,
  },
  {
    provider_id: 'gemini',
    provider_name: 'Gemini',
    is_enabled: true,
    website_url: 'https://gemini.google.com/',
    auth_method: ['google'],
    connection_type: 'https',
    models: [
      {
        id: 'gemini-3.5-flash',
        name: 'Gemini 3.5 Flash',
        is_thinking: false,
        max_context_length: null,
        is_search: false,
        is_image_upload: false,
        is_video_upload: false,
        description:
          'Google Gemini 3.5 Flash - Fast and efficient model for everyday tasks, optimized for quick responses',
      },
      {
        id: 'gemini-3.5-flash-thinking',
        name: 'Gemini 3.5 Flash Thinking',
        is_thinking: true,
        max_context_length: null,
        is_search: false,
        is_image_upload: false,
        is_video_upload: false,
        description:
          'Google Gemini 3.5 Flash Thinking - Enhanced reasoning with step-by-step thinking process for complex problems',
      },
      {
        id: 'gemini-3.5-flash-thinking-lite',
        name: 'Gemini 3.5 Flash Thinking Lite',
        is_thinking: true,
        max_context_length: null,
        is_search: false,
        is_image_upload: false,
        is_video_upload: false,
        description:
          'Google Gemini 3.5 Flash Thinking Lite - Lightweight version with thinking mode, balances speed and depth',
      },
      {
        id: 'gemini-3.1-pro',
        name: 'Gemini 3.1 Pro',
        is_thinking: false,
        max_context_length: null,
        is_search: false,
        is_image_upload: false,
        is_video_upload: false,
        description:
          'Google Gemini 3.1 Pro - Professional-grade model with advanced capabilities for complex tasks',
      },
      {
        id: 'gemini-auto',
        name: 'Gemini Auto',
        is_thinking: false,
        max_context_length: null,
        is_search: false,
        is_image_upload: false,
        is_video_upload: false,
        description:
          'Google Gemini Auto - Automatically selects optimal model based on task complexity and requirements',
      },
      {
        id: 'gemini-flash-lite',
        name: 'Gemini Flash Lite',
        is_thinking: false,
        max_context_length: null,
        is_search: false,
        is_image_upload: false,
        is_video_upload: false,
        description:
          'Google Gemini Flash Lite - Ultra-lightweight model for resource-constrained environments and high throughput',
      },
    ],
    is_pausable: false,
    is_memory: false,
  },
  {
    provider_id: 'groq',
    provider_name: 'Groq',
    is_enabled: true,
    website_url: 'https://groq.com',
    auth_method: ['basic'],
    connection_type: 'https',
    is_pausable: false,
    is_memory: false,
  },
  {
    provider_id: 'huggingchat',
    provider_name: 'HuggingChat',
    is_enabled: true,
    website_url: 'https://huggingface.co/',
    auth_method: ['basic'],
    connection_type: 'https',
    is_pausable: false,
    is_memory: false,
  },
  {
    provider_id: 'kimi',
    provider_name: 'Kimi',
    is_enabled: true,
    website_url: 'https://www.kimi.ai/',
    auth_method: ['basic', 'google'],
    connection_type: 'https',
    is_pausable: false,
    is_memory: false,
    models: [
      {
        id: 'k3',
        name: 'Kimi K3 (Flagship)',
        is_thinking: true,
        max_context_length: 262144,
        is_search: true,
        is_image_upload: true,
        is_video_upload: false,
        description:
          'Kimi K3 Flagship All-Rounder - Chat & Agent with state-of-the-art reasoning and problem solving.',
      },
      {
        id: 'k3-swarm',
        name: 'Kimi K3 Swarm',
        is_thinking: true,
        max_context_length: 262144,
        is_search: true,
        is_image_upload: true,
        is_video_upload: false,
        description:
          'Kimi K3 Swarm - Massive search, batch processing, and multi-agent workflow in one go.',
      },
      {
        id: 'instant',
        name: 'Kimi Instant',
        is_thinking: false,
        max_context_length: 262144,
        is_search: true,
        is_image_upload: true,
        is_video_upload: false,
        description:
          'Kimi Instant - Ultra-fast responses for everyday chat queries.',
      },
      {
        id: 'k2d6-thinking',
        name: 'Kimi K2.6 Thinking',
        is_thinking: true,
        max_context_length: 262144,
        is_search: true,
        is_image_upload: true,
        is_video_upload: false,
        description:
          'Kimi K2.6 Thinking delivers deep reasoning, step-by-step logic deduction, and advanced mathematical problem solving.',
      },
      {
        id: 'k2d6',
        name: 'Kimi K2.6 Instant',
        is_thinking: false,
        max_context_length: 262144,
        is_search: true,
        is_image_upload: true,
        is_video_upload: false,
        description:
          'Kimi K2.6 Instant provides fast text generation for conversational tasks.',
      },
      {
        id: 'k2d6-agent',
        name: 'Kimi K2.6 Agent',
        is_thinking: true,
        max_context_length: 262144,
        is_search: true,
        is_image_upload: true,
        is_video_upload: false,
        description:
          'Kimi K2.6 Agent autonomously performs comprehensive research, slides generation, and document processing.',
      },
      {
        id: 'k2d6-agent-ultra',
        name: 'Kimi K2.6 Agent Swarm',
        is_thinking: true,
        max_context_length: 262144,
        is_search: true,
        is_image_upload: true,
        is_video_upload: false,
        description:
          'Kimi K2.6 Agent Swarm coordinates multi-agent workers for large-scale information retrieval.',
      },
    ],
  },
  {
    provider_id: 'lmarena',
    provider_name: 'LMArena',
    is_enabled: false,
    website_url: 'https://lmarena.ai/',
    auth_method: ['basic'],
    is_pausable: false,
    is_memory: false,
  },
  {
    provider_id: 'mistral',
    provider_name: 'Mistral',
    is_enabled: true,
    website_url: 'https://mistral.ai/',
    auth_method: ['basic'],
    connection_type: 'https',
    is_pausable: false,
    is_memory: false,
  },
  {
    provider_id: 'perplexity',
    provider_name: 'Perplexity',
    is_enabled: true,
    website_url: 'https://www.perplexity.ai/',
    auth_method: ['basic'],
    connection_type: 'https',
    is_pausable: false,
    is_memory: false,
  },
  {
    provider_id: 'qwen',
    provider_name: 'Qwen',
    is_enabled: true,
    website_url: 'https://modelscope.cn/',
    auth_method: ['basic', 'google'],
    connection_type: 'https',
    is_pausable: false,
    is_memory: true,
    models: [
      {
        id: 'qwen-3.8-max',
        name: 'Qwen3.8-Max',
        is_thinking: true,
        max_context_length: 1000000,
        is_search: true,
        is_image_upload: false,
        is_video_upload: false,
        description:
          'Qwen3.8-Max is the flagship model of the Qwen3.8 series, delivering state-of-the-art performance with advanced capabilities in expert-level knowledge, complex logical reasoning, advanced mathematics, and sophisticated coding tasks.',
      },
      {
        id: 'qwen-3.8-plus',
        name: 'Qwen3.8-Plus',
        is_thinking: true,
        max_context_length: 1000000,
        is_search: true,
        is_image_upload: true,
        is_video_upload: true,
        description:
          'Qwen3.8-Plus is a high-performance large language model within the Qwen3.8 family, integrating state-of-the-art text and multimodal processing capabilities. It excels in web development, complex reasoning, role-playing, creative writing, visual reasoning, OCR, and spatial understanding.',
      },
      {
        id: 'qwen-3.7-plus',
        name: 'Qwen3.7-Plus',
        is_thinking: true,
        max_context_length: 1000000,
        is_search: true,
        is_image_upload: true,
        is_video_upload: true,
        description:
          'Qwen3.7-Plus is a high-performance large language model within the Qwen3.7 family, integrating state-of-the-art text and multimodal processing capabilities. It can autonomously invoke tools during everyday conversations and excels in web development, artifacts, complex reasoning, role-playing, creative writing, visual reasoning, OCR, and spatial understanding.',
      },
      {
        id: 'qwen-3.7-max',
        name: 'Qwen3.7-Max',
        is_thinking: true,
        max_context_length: 1000000,
        is_search: true,
        is_image_upload: false,
        is_video_upload: false,
        description:
          'Qwen3.7-Max is the flagship model of the Qwen3.7 series, engineered to deliver state-of-the-art performance and our most advanced capabilities. It excels in expert-level knowledge, complex logical reasoning, advanced mathematics, and sophisticated coding tasks. Please note that it does not currently support vision capabilities.',
      },
      {
        id: 'qwen-3.6-plus',
        name: 'Qwen3.6-Plus',
        is_thinking: true,
        max_context_length: 1000000,
        is_search: true,
        is_image_upload: true,
        is_video_upload: true,
        description:
          'Qwen3.6-Plus is the latest large model in the Qwen3.6 series, integrating state-of-the-art text and multimodal processing capabilities. It can autonomously invoke tools during everyday conversations and excels in web development, artifacts, complex reasoning, role-playing, creative writing, visual reasoning, OCR, and spatial understanding.',
      },
      {
        id: 'qwen-3.6-max-preview',
        name: 'Qwen3.6-Max-Preview',
        is_thinking: true,
        max_context_length: 262144,
        is_search: false,
        is_image_upload: false,
        is_video_upload: false,
        description:
          'Qwen3.6-Max-Preview is a preview version of the flagship model in the Qwen3.6 family, featuring our most advanced text capabilities. It excels in expert-level knowledge, complex reasoning, mathematics, and coding. Please note that this preview build does not currently support Search or Code Interpreter tools.',
      },
      {
        id: 'qwen-3.5-plus',
        name: 'Qwen3.5-Plus',
        is_thinking: true,
        max_context_length: 1000000,
        is_search: true,
        is_image_upload: true,
        is_video_upload: true,
        description:
          'Qwen3.5-Plus is the latest large model in the Qwen3.5 series, integrating state-of-the-art text and multimodal processing capabilities. It can autonomously invoke tools during everyday conversations and excels in complex reasoning, instruction following, programming, role-playing, creative writing, visual reasoning, OCR, and spatial understanding.',
      },
      {
        id: 'qwen-3.5-flash',
        name: 'Qwen3.5-Flash',
        is_thinking: true,
        max_context_length: 1000000,
        is_search: true,
        is_image_upload: true,
        is_video_upload: true,
        description:
          'The latest high-efficiency model in the Qwen3.5 series, supporting text and multimodal tasks. It excels in complex reasoning, instruction following, programming, role-playing, creative writing, visual reasoning, OCR, and spatial understanding.',
      },
      {
        id: 'qwen-max',
        name: 'Qwen-Max',
        is_thinking: true,
        max_context_length: 1000000,
        is_search: true,
        is_image_upload: false,
        is_video_upload: false,
        description:
          'Qwen-Max is the flagship model delivering state-of-the-art performance in complex reasoning and advanced tasks.',
      },
      {
        id: 'qwen-plus',
        name: 'Qwen-Plus',
        is_thinking: true,
        max_context_length: 1000000,
        is_search: true,
        is_image_upload: true,
        is_video_upload: true,
        description:
          'Qwen-Plus is a versatile large model balancing speed and multimodal intelligence.',
      },
      {
        id: 'qwen3-coder-plus',
        name: 'Qwen3-Coder',
        is_thinking: false,
        max_context_length: 1048576,
        is_search: false,
        is_image_upload: true,
        is_video_upload: true,
        description:
          'Qwen3-Coder is a powerful coding-specialized language model excelling in code generation, tool use, and agentic tasks.',
      },
      {
        id: 'qwen3-vl-plus',
        name: 'Qwen3-VL-235B-A22B',
        is_thinking: true,
        max_context_length: 262144,
        is_search: false,
        is_image_upload: true,
        is_video_upload: true,
        description:
          'Qwen3-VL is the most advanced vision-language model in the Qwen series, seamlessly integrating text and vision with no performance trade-off. It excels in visual reasoning, OCR, spatial understanding, and GUI-based agent tasks.',
      },
    ],
  },
  {
    provider_id: 'stepfun',
    provider_name: 'StepFun',
    is_enabled: false,
    website_url: 'https://stepfun.ai/',
    auth_method: ['basic'],
    is_pausable: false,
    is_memory: false,
  },
  {
    provider_id: 'cerebras',
    provider_name: 'Cerebras',
    is_enabled: false,
    website_url: 'https://cerebras.ai/',
    auth_method: ['basic', 'google'],
    is_pausable: false,
    is_memory: false,
  },
  {
    provider_id: 'cerebras-cloud',
    provider_name: 'Cerebras Cloud',
    is_enabled: true,
    website_url: 'https://cloud.cerebras.ai/',
    auth_method: ['basic', 'google'],
    connection_type: 'https',
    is_pausable: false,
    is_memory: false,
  },
  {
    provider_id: 'googlestudio',
    provider_name: 'Google Studio',
    is_enabled: false,
    website_url: 'https://aistudio.google.com/',
    auth_method: ['google'],
    is_pausable: false,
    is_memory: false,
  },
  {
    provider_id: 'z',
    provider_name: 'Z',
    is_enabled: true,
    website_url: 'https://chat.z.ai/',
    auth_method: ['google', 'basic'],
    is_pausable: false,
    is_memory: false,
  },
  {
    provider_id: 'zai-browser',
    provider_name: 'Z.AI Browser',
    is_enabled: true,
    website_url: 'https://chat.z.ai/',
    auth_method: ['google', 'basic'],
    connection_type: 'browser',
    is_pausable: false,
    is_memory: false,
    platform: 'web',
    browser_extension_folder: 'zai-bridge',
    models: [
      {
        id: 'GLM-5.1',
        name: 'GLM-5.1',
        is_thinking: true,
        max_context_length: null,
        is_search: true,
        is_image_upload: false,
        is_video_upload: false,
        description:
          'Z.AI GLM-5.1 - Advanced language model with thinking mode and web search (browser-based)',
      },
      {
        id: 'GLM-5',
        name: 'GLM-5',
        is_thinking: true,
        max_context_length: null,
        is_search: true,
        is_image_upload: false,
        is_video_upload: false,
        description:
          'Z.AI GLM-5 - Fast and efficient model with thinking capabilities (browser-based)',
      },
    ],
  },
  {
    provider_id: 'qwen-cli',
    provider_name: 'Qwen Coder CLI',
    is_enabled: true,
    website_url: 'https://modelscope.cn/',
    auth_method: ['basic'],
    connection_type: 'https',
    models: [
      {
        id: 'coder-model',
        name: 'Coder Model',
        is_thinking: false,
        max_context_length: null,
        is_search: false,
        is_image_upload: false,
        is_video_upload: false,
        description:
          'Qwen Coder Model - Specialized for code generation, debugging, and programming assistance',
      },
    ],
    is_pausable: false,
    is_memory: false,
  },
  {
    provider_id: 'gemini-cli',
    provider_name: 'Gemini CLI',
    is_enabled: true,
    website_url: 'https://gemini.google.com/',
    auth_method: ['google'],
    connection_type: 'https',
    is_pausable: false,
    is_memory: false,
  },
  {
    provider_id: 'iflow-cli',
    provider_name: 'iFlow CLI',
    is_enabled: false,
    website_url: 'https://iflow.ai/',
    auth_method: ['basic'],
    is_pausable: false,
    is_memory: false,
  },
  {
    provider_id: 'codex-cli',
    provider_name: 'Codex CLI',
    is_enabled: true,
    website_url: 'https://google.com/',
    auth_method: ['google', 'basic'],
    connection_type: 'https',
    models: [
      {
        id: 'gpt-5.3-codex',
        name: 'GPT-5.3 Codex',
        is_thinking: false,
        max_context_length: null,
        is_search: false,
        is_image_upload: false,
        is_video_upload: false,
        description:
          'OpenAI GPT-5.3 Codex - Advanced coding model with extensive programming knowledge and problem-solving',
      },
      {
        id: 'gpt-5.2-codex',
        name: 'GPT-5.2 Codex',
        is_thinking: false,
        max_context_length: null,
        is_search: false,
        is_image_upload: false,
        is_video_upload: false,
        description:
          'OpenAI GPT-5.2 Codex - Powerful code generation model with strong reasoning for complex algorithms',
      },
      {
        id: 'gpt-5.1-codex-max',
        name: 'GPT-5.1 Codex Max',
        is_thinking: false,
        max_context_length: null,
        is_search: false,
        is_image_upload: false,
        is_video_upload: false,
        description:
          'OpenAI GPT-5.1 Codex Max - Maximum capacity coding model for large-scale software development',
      },
      {
        id: 'gpt-5.2',
        name: 'GPT-5.2',
        is_thinking: false,
        max_context_length: null,
        is_search: false,
        is_image_upload: false,
        is_video_upload: false,
        description:
          'OpenAI GPT-5.2 - General purpose model with balanced capabilities for diverse tasks',
      },
      {
        id: 'gpt-5.1-codex-mini',
        name: 'GPT-5.1 Codex Mini',
        is_thinking: false,
        max_context_length: null,
        is_search: false,
        is_image_upload: false,
        is_video_upload: false,
        description:
          'OpenAI GPT-5.1 Codex Mini - Compact coding assistant for quick iterations and lightweight tasks',
      },
    ],
    is_pausable: false,
  },
];
